version: '2.0'
services:
  rabbit:
     container_name: mysystem_acceptancetests_rabbit
     hostname: rabbit
     image: rabbitmq:3.6.6-management
     environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
     ports:
        - "5672:5672"
        - "15672:15672"